Name: Makefile
Type: requirement
Invented on: 2010-02-14
Invented by: flonatel
Owner: development
Description: Automatic generation of artifacts \textbf{must} be
 possible by using a Makefile.
Rationale: This gives the users a simple to 'make all' thing, which in
 turn calls the needed commands.
Status: not done
Class: implementable
Priority: customers:8
Effort estimation: 5
Topic: AutoCreationOfArtifacts
Solved by: MakefileDeps
# Added by rmtoo-normalize-dependencies
