Document: rmtoo
Title: Debian rmtoo Manual
Author: <insert document author here>
Abstract: This manual describes what rmtoo is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rmtoo/rmtoo.sgml.gz

Format: postscript
Files: /usr/share/doc/rmtoo/rmtoo.ps.gz

Format: text
Files: /usr/share/doc/rmtoo/rmtoo.text.gz

Format: HTML
Index: /usr/share/doc/rmtoo/html/index.html
Files: /usr/share/doc/rmtoo/html/*.html


